# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: grafana
    image: grafana/grafana:6.7.3
    restart: always
    volumes:
      - /Users/hgao/Mine/soft/docker/volumes/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
