version: '3.1'

services:
  kafka:
    container_name: mykafka
    image: spotify/kafka
    hostname: kafka
    ports:
      - 9092:9092
      #- 2221:2181
      - 2181:2181
    environment:
      ADVERTISED_HOST: 127.0.0.1
      # ADVERTISED_HOST: 172.20.29.54
      ADVERTISED_PORT: 9092
    volumes:
      # - /Users/hgao/Mine/soft/docker/volumes/kafka/kafka/data/config:/opt/kafka_2.11-0.10.1.0/config
      - /Users/hgao/Mine/soft/docker/volumes/kafka/kafka/data/kafka-log:/tmp/kafka-logs

  kafka-manager:
    container_name: my_kafka_manager
    image: sheepkiller/kafka-manager
    restart: always
    hostname: kafka-manager
    ports:
      - 9000:9000
    environment:
      APPLICATION_SECRET: letmein
      ZK_HOSTS: "kafka:2181"
    # volumes:
      # - /Users/hgao/Mine/soft/docker/volumes/kafka/kafka/data/kafka-log:/tmp/kafka-logs
