# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mymysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --lower_case_table_names=1
    restart: always
    volumes:
      - /Users/hgao/Mine/soft/docker/volumes/mysql/data:/var/lib/mysql
      - /Users/hgao/Mine/soft/docker/volumes/mysql/datasets:/opt/datasets
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  # adminer:
    # image: adminer
    # restart: always
    # ports:
    #   - 18080:8080
