# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:12.2
    restart: always
    # volumes:
    #   - /Users/hgao/Mine/soft/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
